apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 889168908024.dkr.ecr.ap-south-1.amazonaws.com/frontend:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: VITE_API_URL
          value: "http://a99740ee92415435f9abe6c44d7a620b-1171611830.ap-south-1.elb.amazonaws.com"
        
